# Generated by Django 2.2.7 on 2021-01-06 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_auto_20200501_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 12, 17, 32, 166843)),
        ),
    ]
